# Generated by Django 3.2.7 on 2021-09-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptinfo',
            name='rctno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
